[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  VITE_API_URL = "https://www.hnvpm.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://hnv-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Subdomain redirects
[[redirects]]
  from = "https://login.hnvpm.com/*"
  to = "https://www.hnvpm.com/login"
  status = 301
  force = true

[[redirects]]
  from = "https://register.hnvpm.com/*"
  to = "https://www.hnvpm.com/register"
  status = 301
  force = true

[[redirects]]
  from = "https://admin.hnvpm.com/*"
  to = "https://www.hnvpm.com/admin"
  status = 301
  force = true

[[redirects]]
  from = "https://app.hnvpm.com/*"
  to = "https://www.hnvpm.com/dashboard"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"