services:
  - type: web
    name: hnv-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        fromDatabase:
          name: hnv-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://www.hnvpm.com
      - key: BACKEND_URL
        value: https://hnv-property.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: HNV Property Management <noreply@hnvpm.com>
      - key: CONTACT_EMAIL
        value: contact@hnvpm.com

  - type: web
    name: hnv-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hnv-backend.onrender.com/api
    domains:
      - www.hnvpm.com
      - hnvpm.com
      - login.hnvpm.com
      - register.hnvpm.com
      - admin.hnvpm.com
      - app.hnvpm.com
      - dashboard.hnvpm.com

databases:
  - name: hnv-mongodb
    databaseName: hnv-saas
    user: hnv-user