services:
  - type: web
    name: hnv-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install --production && echo 'Build complete - using existing JS files'
    startCommand: node ./backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        fromDatabase:
          name: hnv-mongodb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hnv-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://hnv-frontend.onrender.com

  - type: web
    name: hnv-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npx vite build
    staticPublishPath: frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://hnv-backend.onrender.com

databases:
  - name: hnv-mongodb
    databaseName: hnv_production
    user: hnv_user
    plan: starter

  - name: hnv-redis
    plan: starter