services:
  - type: web
    name: hnv-saas-backend
    env: docker
    plan: standard
    repo: https://github.com/your-org/hnv-saas
    branch: main
    rootDir: backend
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: (your-mongo-connection-string)
      # ... other env vars ...

  - type: static
    name: hnv-saas-frontend
    repo: https://github.com/your-org/hnv-saas
    branch: main
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hnv-saas-backend.onrender.com/api