services:
  - type: web
    name: hnv-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        fromDatabase:
          name: hnv-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://hnv-frontend.onrender.com
      - key: BACKEND_URL
        value: https://hnv-backend.onrender.com

  - type: web
    name: hnv-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hnv-backend.onrender.com/api

databases:
  - name: hnv-mongodb
    databaseName: hnv-saas
    user: hnv-user