openapi: 3.0.0
info:
  title: HNV SaaS API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: User login
      requestBody:
        ...
      responses:
        '200':
          description: Success